apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-l2-rbac
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-lab
  source:
    repoURL: https://gitlab.bevz.net/abevz/platform-iac-gitops.git
    targetRevision: main
    path: k8s-lab-01/cilium-l2-rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
