apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
spec:
  project: platform-lab
  source:
    repoURL: https://gitlab.bevz.net/abevz/platform-iac-gitops.git
    targetRevision: main
    path: k8s-lab-01/external-secrets-config
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
