apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-lab
  namespace: argocd
spec:
  description: Platform GitOps project for k8s-lab-01
  sourceRepos:
    - https://gitlab.bevz.net/abevz/platform-iac-gitops.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
