apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-sandbox-example
  namespace: sandbox-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vault-sandbox-example
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: sandbox/eso-example
        property: value
