apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-creds
  namespace: demo-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: registry-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"harbor.example.com":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}'
  data:
    - secretKey: username
      remoteRef:
        key: ci/harbor
        property: username
    - secretKey: password
      remoteRef:
        key: ci/harbor
        property: password
