apiVersion: apps/v1
kind: Deployment
metadata:
  name: democicd
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democicd
  template:
    metadata:
      labels:
        app: democicd
    spec:
      containers:
        - name: democicd
          image: harbor.bevz.net/demo/democicd:6b006796
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "latest"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
